%YAML 1.2
%TAG !n! tag:nimyaml.org,2016:
--- !n!custom:MonitorConfig 
sleep: 1
targets: 
  - 
    name: Build Slides
    paths: [src]
    commands: [nimble build, ./bin/nimconf2024]
    extensions: [.nim]
    files: []
    exclude_extensions: []
    exclude_files: []
    once: true

